[project]
authors = ["Derek Smith <derekcs@pm.me>"]
channels = ["conda-forge", "https://conda.modular.com/max"]
description = "Add a short description here"
name = "automajo"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
max = ">=24.5.0,<25"
